apiVersion: v1
kind: ConfigMap
metadata:
  name: waha-config
  namespace: apps
data:
  WHATSAPP_DEFAULT_ENGINE: "WEBJS"
  WAHA_PRINT_QR: "False"
  WAHA_MEDIA_STORAGE: "LOCAL"
  WHATSAPP_FILES_LIFETIME: "0"
  WHATSAPP_FILES_FOLDER: "/app/.media"
  N8N_BASE_URL: "http://n8n:5678"
