apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - secret.yaml
  - configmap.yaml
  - pvc-sessions.yaml
  - pvc-media.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml  # uncomment if you want external access
