apiVersion: v1
kind: Service
metadata:
  name: ngrok-hello
  namespace: ngrok-operator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8002
  selector:
    app: ngrok-hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok-hello
  template:
    metadata:
      labels:
        app: ngrok-hello
    spec:
      containers:
        - name: backend
          image: shubcodes/ngrok-hello:latest
          ports:
            - name: http
              containerPort: 8002