apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ngrok-hello-ingress
spec:
  ingressClassName: ngrok
  rules:
    - host: "relevant-finch-dynamic.ngrok-free.app"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ngrok-hello
                port:
                  number: 80