services:
  rwmarkable:
    image: ghcr.io/fccview/rwmarkable:latest
    container_name: rwmarkable
    user: "1000:1000"
    ports:
      - "1122:3000"
    volumes:
      - /srv/docker/rwmarkable/data:/app/data:rw
      - /srv/docker/rwmarkable/config:/app/config:ro
      - /srv/docker/rwmarkable/cache:/app/.next/cache:rw
    restart: unless-stopped
    #platform: linux/arm64
    environment:
      - NODE_ENV=production
      #- HTTPS=true
      #- SERVE_PUBLIC_IMAGES=yes
      #- SERVE_PUBLIC_FILES=yes
      #- SSO_MODE=oidc
      #- OIDC_ISSUER=<YOUR_SSO_ISSUER>
      #- OIDC_CLIENT_ID=<YOUR_SSO_CLIENT_ID>
      #- APP_URL=https://your-rwmarkable-domain.com
      #- OIDC_CLIENT_SECRET=your_client_secret
      #- SSO_FALLBACK_LOCAL=true
      #- OIDC_ADMIN_GROUPS=admins
